# Generated by Django 4.0.4 on 2022-04-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_teller_delete_customers_customer_teller'),
    ]

    operations = [
        migrations.AddField(
            model_name='teller',
            name='profile',
            field=models.ImageField(default='avatar.png', upload_to='profile'),
        ),
    ]
