# Generated by Django 4.0.4 on 2022-04-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_expired_date_teller_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='expired_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
